# -*- coding: utf-8 -*-
"""Day 1 python basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13RMERLZsZz3QUarIZ_-hfZjKcod8D1of
"""

print("I am not lazy anymore")
a=5
print(a)
name = input("what is your name: ")
age = input("what is your age: ")
print("you will be 100 in " , 100-int(age) , " years")

for i in range(1,11):
  print(i)

for i in range(10):
  print("Taran")

for i in range(2,21,2):
  print(i)

num = int(input("Enter your number: "))
if num >10:
  print("Big number")
else:
  print("Small number")

marks = int(input("Enter your marks: "))
if marks >= 40:
  print("PASS")
else:
  print("FAIL")

sub_1 = int(input("Enter your marks for subject 1: "))
sub_2 = int(input("Enter you marks for subject 2: "))
sub_3 = int(input("Enter your marks for subject 3: "))
average = (sub_1+sub_2+sub_3)/3
if average  >= 40:
  print("Pass")
else:
  print("Fail")
if sub_1 >=90 and sub_2>=90 and sub_3>=90:
  print("Topper")